trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    git clone https://github.com/rubelbinu/AeroWatch--Capstone-Project.git
    cd <AeroWatch--Capstone-Project>
    git remote add azure https://dev.azure.com/Vshetty0153/_git/AeroWatch-%20Capstone%20Project
    git push azure --mirror
  displayName: 'Sync GitHub to Azure DevOps'
